# Generated by Django 3.2.4 on 2021-06-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_student_gander'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
