# Generated by Django 3.2.4 on 2021-06-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
    ]
